### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by kerravon86** [utshina/uefi-simple#4]
Hello.

There is currently no license, no copyright and no public domain notice.

Meaning by default it is copyright, and nothing allows anyone to use it.

Could you please add a "released to the public domain" notice in your code, without caveats, so that it can be used without restriction?

Or if not, then a copyright notice with whatever the restrictions are.

Thanks.

**Comment by utshina** [comment]
I've added the LICENSE file for CC0.
Thanks for pointing that out.

**Comment by kerravon86** [comment]
Thankyou!
